# roles/db/tasks/main.yml
---
- name: "Show info about the env this host belongs to"
  debug:
    msg: "This host is in {{ env }} environment"
- name: Change mongo config file
  template:
    # see the manual, no folder name here
    src: mongod.conf.j2
    # sure, not mongod but mongodb
    # thanks to 403 and all that stuff
    dest: /etc/mongodb.conf
    # some text file for everyone to read
    mode: 0644
  notify: restart mongod

- include: install_mongo.yml
- include: config_mongo.yml
